scene-mesh:
  facade:
    url:
      mqtt: mqtt://127.0.0.1:1883
      websocket: ws://127.0.0.1:8888
spring:
  application:
    name: scene-mesh-benchmark
  profiles:
    active: dev
  main:
    web-application-type: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

# 日志配置
logging:
  level:
    com.scene.mesh.benchmark: DEBUG
    com.scene.mesh.service: INFO
    com.scene.mesh.model: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/scene-mesh-benchmark.log
